In [45]:
def fibo(n):
    if n == 0 :
        return 0
    elif n == 1 or n == 2:
        return 1
    else: return fibo(n-1) + fibo(n-2)
    
print(fibo(9))

34


In [46]:
def fibo2(n):
    cur, next_ = 0, 1
    for x in range(n):
        cur, next_ = next_, cur + next_
    return cur
fibo2(40)

102334155

In [49]:
%%time
fibo(40)

Wall time: 29.6 s


102334155

In [50]:
def fib3(m, n):
    if m[n] == 0:
        m[n] = fib3(m, n-1) + fib3(m, n-2)
    return m[n]

In [52]:
%%time
n = 40
m = [0] * n
m[0], m[1] = 1, 1
print(fib3(m, n-1))

102334155
Wall time: 0 ns


In [65]:
import numpy as np

In [54]:
np.__version__

'1.20.1'

In [55]:
np.array([1,2,3])

array([1, 2, 3])

In [66]:
import random

In [72]:
random.seed(10)
list_a = [random.randrange(1,100) for x in range(100000000)]

In [73]:
np_a = np.array(list_a)

In [74]:
%%time
list_a = [i+100 for i in list_a]

Wall time: 5.4 s


In [5]:
a = np.array([1,2,3])

In [6]:
type(a)

numpy.ndarray

In [7]:
a + 10

array([11, 12, 13])

In [10]:
a * 10

array([10, 20, 30])

In [11]:
a2 = np.array([[1,2,3], [4,5,6]])

In [15]:
a2.ndim

2

In [16]:
a2.shape

(2, 3)

In [17]:
a2.dtype

dtype('int32')

In [18]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
import pandas as pd

In [21]:
s_a = pd.Series([1,2,3])

In [23]:
type(s_a)

pandas.core.series.Series

In [24]:
s_a.values

array([1, 2, 3], dtype=int64)

In [25]:
df_a = pd.DataFrame({"a" : [1,2,3], "b"  : [2,3,4]})

In [28]:
df_a['a'].values

array([1, 2, 3], dtype=int64)

In [32]:
pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']], columns=['나이', '성별', '학교'], index=['준서', '예은'])

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [33]:
df2 = pd.DataFrame({"나이": [15,17], "성별" : ['남', '여'], '학교' : ['덕영중','수리중']}, index=['준서', '예은'])

In [35]:
df2

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [36]:
df2['나이'].values

array([15, 17], dtype=int64)

In [37]:
df2.iloc[0,:]

나이     15
성별      남
학교    덕영중
Name: 준서, dtype: object

In [38]:
df2.iloc[0,:].values

array([15, '남', '덕영중'], dtype=object)

In [44]:
kbo = pd.read_csv("./kbo.csv")

In [45]:
kbo

선수명   등번호           생년월일        포지션        신장/체중                    경력  \
0    강동연  21.0  1992년 12월 18일   투수(우투우타)   195cm/94kg  진북초-덕수중-유신고-두산-상무-두산   
1    강진성  49.0  1993년 10월 19일  내야수(우투우타)   180cm/81kg     가동초-잠신중-경기고-NC-경찰   
2    강태경  78.0  2001년 07월 26일   투수(우투좌타)   188cm/95kg           양덕초-잠실중-배명고   
3    구창모  59.0  1997년 02월 17일   투수(좌투좌타)   183cm/85kg        천안남산초-덕수중-울산공고   
4    권법수  65.0  1997년 04월 05일  외야수(우투우타)   183cm/82kg          선학초-재능중-제물포고   
..   ...   ...            ...        ...          ...                   ...   
852  하주석  16.0  1994년 02월 25일  내야수(우투좌타)   184cm/84kg     강남초-덕수중-신일고-한화-상무   
853  한승주  59.0  2001년 03월 17일   투수(우투우타)   184cm/82kg         부산수영초-대천중-부산고   
854  허관회  26.0  1999년 02월 12일   포수(우투우타)   176cm/83kg   경동초(의정부리틀)-건대부중-경기고   
855  황영국  60.0  1995년 12월 26일   투수(좌투좌타)   185cm/83kg   청주우암초-청주중-청주고-한화-경찰   
856   힐리   NaN  1992년 01월 10일  내야수(우투우타)  195cm/104kg       미국 Oregon(대)-한화   

       입단 계약금        연봉                지명순위  입단년도  
0         NaN    4400만원          11 두산 육성선수  12두산  
1      7000만원   12000만원     12 NC 4라운드 33순위  12NC  
2      7000만원    3000만원  20 NC 2차 5라운드 41순위  21NC  
3     15000만원   25000만원   15 NC 2차 1라운드 3순위  15NC  
4      5000만원    3000만원  17 NC 2차 6라운드 58순위  17NC  
..        ...       ...                 ...   ...  
852   30000만원   13500만원      12 한화 1라운드 1순위  12한화  
853   11000만원    3000만원  20 한화 2차 2라운드 18순위  20한화  
854    3000만원    3100만원  19 한화 2차 9라운드 83순위  20한화  
855   20000만원    3300만원            14 한화 1차  14한화  
856  300000달러  500000달러          21 한화 자유선발  21한화  

[857 rows x 10 columns]

In [43]:
type(kbo)

pandas.core.frame.DataFrame

In [ ]:

## 과제 1 -> txt 파일안에 금앨을 남성, 여성으로 구분해서 토탈값 구하기

## 과제 2 -> txt파일 10000개를 남성, 여성폴더 생성하고 해당폴더에 파일 옮기기

In [46]:
import shutil

In [47]:
shutil.move(""./a.txt", "./b/a.txt")

SyntaxError: invalid syntax (<ipython-input-47-2fb4214b53a6>, line 1)

In [48]:
import os

In [54]:
file.split("_")[2][0]

'4'

In [85]:
mTotal = []
fTotal = []
for roots, dirs, files in os.walk("./이름_생년_성별_10000"):
    if not os.path.isdir("./남성"):
        os.mkdir("./남성")
    if not os.path.isdir("./여성"):
        os.mkdir("./여성")
    for file in files:
        if file.split("_")[2][0] in ['1', '3']:
            with open(roots + "/" + file) as f:
                for x in f:
                    mTotal.append(x.replace(",", ""))
            shutil.move(roots + "/" + file, "./남성" + file)
        else:
            with open(roots + "/" + file) as f:
                for x in f:
                    fTotal.append(x.replace(",", ""))
            shutil.move(roots + "/" + file, "./여성" + file)

In [81]:
mTotal = list(map(int, mTotal))

In [69]:
mTotal

[10251,
 83057,
 11812,
 8832673,
 16807288,
 463874,
 9569,
 20961610,
 2633,
 20639,
 9100,
 94208805,
 89931192,
 73812,
 9657,
 7150,
 70032370,
 846546,
 3614098,
 40117946,
 8465939,
 66349,
 74603,
 22614,
 13193909,
 278299,
 34732,
 12537,
 582332,
 3045,
 284,
 403578,
 546030,
 30063,
 20366020,
 8605,
 181718,
 79182,
 2899,
 51727,
 557133,
 9553,
 3323,
 78834032,
 322,
 6080,
 355215,
 145199,
 399341,
 951616,
 52708543,
 93114144,
 60980289,
 26862,
 750779,
 28668,
 760,
 973392,
 55,
 6437,
 4438,
 1435,
 11166,
 1910,
 84185,
 1591,
 59708357,
 752,
 735689,
 90859,
 48813,
 59504366,
 5688,
 7056,
 5133,
 1359,
 17652,
 72976,
 90925,
 998161,
 19747,
 72497266,
 94970697,
 361331,
 3198,
 544362,
 53317,
 6978723,
 6845,
 37043,
 949439,
 115462,
 24971,
 63850,
 95839561,
 41229,
 81495,
 99307148,
 760,
 4743,
 4629,
 4900,
 431835,
 42107335,
 516131,
 80162,
 54057,
 973257,
 51944,
 186022,
 18022,
 56305813,
 3624,
 96783,
 12528,
 266011,
 30110696,
 29171,

In [80]:
fTotal = list(map(int, fTotal))

In [71]:
sum(mTotal)

59417587318

In [75]:
sum(fTotal)

64101458996

In [82]:
mail = """선배님 안녕하세요. 부탁하신 내용 정리합니다.
남성의 총 합은 {}입니다. 여성은 {}입니다.
남성은 총 {}명, 여성은 {}명
""".format(sum(mTotal), sum(fTotal), len(mTotal), len(fTotal))

In [83]:
print(mail)

선배님 안녕하세요. 부탁하신 내용 정리합니다.
남성의 총 합은 59417587318입니다. 여성은 64101458996입니다.
남성은 총 4993명, 여성은 5007명



In [86]:
""" 이메일 보내는 코드 """

' 이메일 보내는 코드 '

In [18]:
import requests
import xml.etree.ElementTree as ET
from urllib import parse

In [50]:
url = "http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19InfStateJson?serviceKey=WRvGBkn9UEtw%2BAsg0tYo210Etxvb1QEcAX%2BwfWvOxVGYJkh1CNZ%2FY4QFa0r7j4bhT4NjPu7z1i1ck8ZgsKMt2Q%3D%3D&pageNo=1&numOfRows=10&startCreateDt=20200310&endCreateDt=20210907"


In [51]:
result = parse.urlparse(url)

In [52]:
result

ParseResult(scheme='http', netloc='openapi.data.go.kr', path='/openapi/service/rest/Covid19/getCovid19InfStateJson', params='', query='serviceKey=WRvGBkn9UEtw%2BAsg0tYo210Etxvb1QEcAX%2BwfWvOxVGYJkh1CNZ%2FY4QFa0r7j4bhT4NjPu7z1i1ck8ZgsKMt2Q%3D%3D&pageNo=1&numOfRows=10&startCreateDt=20200310&endCreateDt=20210907', fragment='')

In [53]:
myquery = parse.parse_qs(result.query)

In [54]:
myquery['pageNo'] = ['2']

In [55]:
myquery

{'serviceKey': ['WRvGBkn9UEtw+Asg0tYo210Etxvb1QEcAX+wfWvOxVGYJkh1CNZ/Y4QFa0r7j4bhT4NjPu7z1i1ck8ZgsKMt2Q=='],
 'pageNo': ['2'],
 'numOfRows': ['10'],
 'startCreateDt': ['20200310'],
 'endCreateDt': ['20210907']}

In [56]:
parse.urlencode(myquery, doseq=True)

'serviceKey=WRvGBkn9UEtw%2BAsg0tYo210Etxvb1QEcAX%2BwfWvOxVGYJkh1CNZ%2FY4QFa0r7j4bhT4NjPu7z1i1ck8ZgsKMt2Q%3D%3D&pageNo=2&numOfRows=10&startCreateDt=20200310&endCreateDt=20210907'

In [57]:
r = requests.get(url)

In [58]:
url

'http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19InfStateJson?serviceKey=WRvGBkn9UEtw%2BAsg0tYo210Etxvb1QEcAX%2BwfWvOxVGYJkh1CNZ%2FY4QFa0r7j4bhT4NjPu7z1i1ck8ZgsKMt2Q%3D%3D&pageNo=1&numOfRows=10&startCreateDt=20200310&endCreateDt=20210907'

In [59]:
root = ET.fromstring(r.text)

In [60]:
items = root.iter(tag='item')

In [61]:
items = root.iter(tag='item')
total = []
for element in items:
    covid_dict = dict()
    for x in element:
        covid_dict[x.tag] = x.text
    total.append(covid_dict)

In [62]:
len(total)

547

In [68]:
covid_df = pd.DataFrame(total)

In [70]:
covid_df.to_csv("./covid_today.csv", index=False, encoding='utf-8')

In [72]:
covid_df.to_excel("./covid.xlsx", index=False, engine='openpyxl')

In [73]:
# DB에 Insert

In [88]:
import sqlite3

In [89]:
conn = sqlite3.connect("./covid.db")

In [90]:
create_table = """
    CREATE TABLE covid19 (
        `accDefRate` DOUBLE(15,10),
        `accExamCnt` INT(4),
        `accExamCompCnt` INT(4),
        `careCnt`      INT(4),
        `clearCnt`     INT(4),
        `createDt`     DATETIME, 
        `deathCnt`     INT(4),
        `decideCnt`    INT(4),
        `examCnt`      INT(4),
        `resutlNegCnt` INT(4),
        `seq`          INT(4),
        `stateDt`      DATE,
        `stateTime`    TIME,
        `updateDt`     DATETIME
    ) 
"""


In [91]:
conn.execute(create_table)

OperationalError: table covid19 already exists

In [78]:
conn.commit()

In [94]:
sql = """INSERT INTO covid19 (accDefRate, accExamCnt, accExamCompCnt, 
         careCnt, clearCnt, createDt, deathCnt, decideCnt, examCnt, resutlNegCnt, seq, stateDt, stateTime, updateDt) VALUES
         (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
"""


In [95]:
for idx, cont in covid_df.iterrows():
    print(cont)
    conn.execute(sql, cont.tolist())
conn.commit()

accDefRate                   2.0933545487
accExamCnt                       13468416
accExamCompCnt                   12581433
careCnt                             25819
clearCnt                           235225
createDt          2021-09-07 09:39:03.178
deathCnt                             2330
decideCnt                          263374
examCnt                            886983
resutlNegCnt                     12318059
seq                                   628
stateDt                          20210907
stateTime                           00:00
updateDt                             null
Name: 0, dtype: object
accDefRate                   2.0899643437
accExamCnt                       13416747
accExamCompCnt                   12525429
careCnt                             25755
clearCnt                           233695
createDt          2021-09-06 09:43:09.889
deathCnt                             2327
decideCnt                          261777
examCnt                            891318
resutlNegCn

In [81]:
cont.tolist()

['2.0933545487',
 '13468416',
 '12581433',
 '25819',
 '235225',
 '2021-09-07 09:39:03.178',
 '2330',
 '263374',
 '886983',
 '12318059',
 '628',
 '20210907',
 '00:00',
 'null']

In [98]:
for row in conn.execute("select * from covid19"):
    print(row)

(2.0933545487, 13468416, 12581433, 25819, 235225, '2021-09-07 09:39:03.178', 2330, 263374, 886983, 12318059, 628, 20210907, '00:00', 'null')
(2.0899643437, 13416747, 12525429, 25755, 233695, '2021-09-06 09:43:09.889', 2327, 261777, 891318, 12263652, 627, 20210906, '00:00', '2021-09-07 10:25:49.129')
(2.0818764374, 13382737, 12508043, 25747, 232334, '2021-09-05 10:48:36.114', 2321, 260402, 874694, 12247641, 626, 20210905, '00:00', '2021-09-07 10:25:39.033')
(2.0713249985, 13350360, 12499825, 26192, 230405, '2021-09-04 09:41:36.458', 2315, 258912, 850535, 12240913, 624, 20210904, '00:00', '2021-09-07 10:25:27.26')
(2.0632216938, 13286680, 12461482, 26182, 228618, '2021-09-03 09:44:30.979', 2308, 257108, 825198, 12204374, 623, 20210903, '00:00', '2021-09-07 10:25:17.938')
(2.0590837722, 13223514, 12403575, 26875, 226222, '2021-09-02 09:37:25.055', 2303, 255400, 819939, 12148175, 622, 20210902, '00:00', '2021-09-07 10:24:49.687')
(2.0486274489, 13152140, 12371161, 26828, 224319, '2021-09-0

In [99]:
pd.read_sql_query("select * from covid19", conn)

accDefRate  accExamCnt  accExamCompCnt  careCnt  clearCnt  \
0      2.093355    13468416        12581433    25819    235225   
1      2.089964    13416747        12525429    25755    233695   
2      2.081876    13382737        12508043    25747    232334   
3      2.071325    13350360        12499825    26192    230405   
4      2.063222    13286680        12461482    26182    228618   
..          ...         ...             ...      ...       ...   
542    3.318000      261335          243701     7402       714   
543    3.458499      248647          230707     7470       510   
544    3.621744      234998          217271     7407       333   
545    3.804175      222395          203855     7212       288   
546    3.919308      210144          191692     7165       247   

                    createDt  deathCnt  decideCnt  examCnt  resutlNegCnt  seq  \
0    2021-09-07 09:39:03.178      2330     263374   886983      12318059  628   
1    2021-09-06 09:43:09.889      2327     261777   891318      12263652  627   
2    2021-09-05 10:48:36.114      2321     260402   874694      12247641  626   
3    2021-09-04 09:41:36.458      2315     258912   850535      12240913  624   
4    2021-09-03 09:44:30.979      2308     257108   825198      12204374  623   
..                       ...       ...        ...      ...           ...  ...   
542   2020-03-14 10:29:11.11        72       8086    17634        235615   73   
543   2020-03-13 10:07:22.22        67       7979    17940        222728   72   
544   2020-03-12 10:37:03.03        66       7869    17727        209402   71   
545   2020-03-11 10:17:19.19        60       7755    18540        196100   70   
546   2020-03-10 10:20:27.27        54       7513    18452        184179   69   

      stateDt stateTime                 updateDt  
0    20210907     00:00                     null  
1    20210906     00:00  2021-09-07 10:25:49.129  
2    20210905     00:00  2021-09-07 10:25:39.033  
3    20210904     00:00   2021-09-07 10:25:27.26  
4    20210903     00:00  2021-09-07 10:25:17.938  
..        ...       ...                      ...  
542  20200314     00:00   2020-03-14 10:29:11.11  
543  20200313     00:00   2020-03-13 10:07:22.22  
544  20200312     00:00   2020-03-12 10:37:03.03  
545  20200311     00:00   2020-03-11 10:17:19.19  
546  20200310     00:00   2020-03-10 10:20:27.27  

[547 rows x 14 columns]

In [100]:
head = {"User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36"}

In [101]:
r = requests.get("https://finance.naver.com/item/sise_day.nhn?code=005930", headers = head)

In [102]:
r.text

'\n<html lang="ko">\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">\n<title>네이버 금융</title>\n\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20210906154844/css/newstock.css">\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20210906154844/css/common.css">\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20210906154844/css/layout.css">\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20210906154844/css/main.css">\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20210906154844/css/newstock2.css">\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20210906154844/css/newstock3.css">\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20210906154844/css/world.css">\n</head>\n<body>\n<script